"""Import Definitions.

Groups:
:::::::::::::::::::

- 1: Healthy controls
- 2: Schizophrenia
- 17: Alzheimer's Disease
"""
DISEASE_LABEL_LIST = [
    2,
    17,
]

VALIDATION_DATASETS = [
    # AD
    "AIBL-SCANNER01",

    # SZ
    "MCIC-SCANNER01",
    "MCIC-SCANNER02",
    "MCIC-SCANNER03",
    "COBRE-SCANNER01",
]

DISEASE_NAME_LIST = [
    "Full Blown Psychosis",
    "Alzheimer's Disease",
]

DISEASE_DICT = {
    1: "Healthy Controls",
    2: "Full Blown Psychosis",
    17: "Alzheimer's Disease",
}

DISEASE_DICT_ABREVIATIONS = {
    2: "SCZ",
    17: "AD",
}

DISEASE_ABBREVIATION_LIST = [
    "SCZ",
    "AD",
]

COLOR_LIST = [
    '#00999E',
    '#0c979c',
    '#259397',
    '#508c90',
    '#66898c',
    '#71878a',
    '#8c8385',
    '#9b8082',
    '#a17f81',
    '#b27c7e',
    '#d87677',
    '#ec7373',
    '#FF7070',
]

QC_FEATURES = [
    "cjv",
    "cnr",
    "efc",
    "fber",
    "fwhm_avg",
    "fwhm_x",
    "fwhm_y",
    "fwhm_z",
    "icvs_csf",
    "icvs_gm",
    "icvs_wm",
    "inu_med",
    "inu_range",
    "qi_1",
    "qi_2",
    "rpve_csf",
    "rpve_gm",
    "rpve_wm",
    "size_x",
    "size_y",
    "size_z",
    "snr_csf",
    "snr_gm",
    "snr_total",
    "snr_wm",
    "snrd_csf",
    "snrd_gm",
    "snrd_total",
    "snrd_wm",
    "spacing_x",
    "spacing_y",
    "spacing_z",
    "summary_bg_k",
    "summary_bg_mad",
    "summary_bg_mean",
    "summary_bg_median",
    "summary_bg_n",
    "summary_bg_p05",
    "summary_bg_p95",
    "summary_bg_stdv",
    "summary_csf_k",
    "summary_csf_mad",
    "summary_csf_mean",
    "summary_csf_median",
    "summary_csf_n",
    "summary_csf_p05",
    "summary_csf_p95",
    "summary_csf_stdv",
    "summary_gm_k",
    "summary_gm_mad",
    "summary_gm_mean",
    "summary_gm_median",
    "summary_gm_n",
    "summary_gm_p05",
    "summary_gm_p95",
    "summary_gm_stdv",
    "summary_wm_k",
    "summary_wm_mad",
    "summary_wm_mean",
    "summary_wm_median",
    "summary_wm_n",
    "summary_wm_p05",
    "summary_wm_p95",
    "summary_wm_stdv",
    "tpm_overlap_csf",
    "tpm_overlap_gm",
    "tpm_overlap_wm",
    "wm2max",
]

COLUMNS_NAME = ['Left-Lateral-Ventricle',
                'Left-Inf-Lat-Vent',
                'Left-Cerebellum-White-Matter',
                'Left-Cerebellum-Cortex',
                'Left-Thalamus-Proper',
                'Left-Caudate',
                'Left-Putamen',
                'Left-Pallidum',
                '3rd-Ventricle',
                '4th-Ventricle',
                'Brain-Stem',
                'Left-Hippocampus',
                'Left-Amygdala',
                'CSF',
                'Left-Accumbens-area',
                'Left-VentralDC',
                'Right-Lateral-Ventricle',
                'Right-Inf-Lat-Vent',
                'Right-Cerebellum-White-Matter',
                'Right-Cerebellum-Cortex',
                'Right-Thalamus-Proper',
                'Right-Caudate',
                'Right-Putamen',
                'Right-Pallidum',
                'Right-Hippocampus',
                'Right-Amygdala',
                'Right-Accumbens-area',
                'Right-VentralDC',
                'CC_Posterior',
                'CC_Mid_Posterior',
                'CC_Central',
                'CC_Mid_Anterior',
                'CC_Anterior',
                'lh_bankssts_volume',
                'lh_caudalanteriorcingulate_volume',
                'lh_caudalmiddlefrontal_volume',
                'lh_cuneus_volume',
                'lh_entorhinal_volume',
                'lh_fusiform_volume',
                'lh_inferiorparietal_volume',
                'lh_inferiortemporal_volume',
                'lh_isthmuscingulate_volume',
                'lh_lateraloccipital_volume',
                'lh_lateralorbitofrontal_volume',
                'lh_lingual_volume',
                'lh_medialorbitofrontal_volume',
                'lh_middletemporal_volume',
                'lh_parahippocampal_volume',
                'lh_paracentral_volume',
                'lh_parsopercularis_volume',
                'lh_parsorbitalis_volume',
                'lh_parstriangularis_volume',
                'lh_pericalcarine_volume',
                'lh_postcentral_volume',
                'lh_posteriorcingulate_volume',
                'lh_precentral_volume',
                'lh_precuneus_volume',
                'lh_rostralanteriorcingulate_volume',
                'lh_rostralmiddlefrontal_volume',
                'lh_superiorfrontal_volume',
                'lh_superiorparietal_volume',
                'lh_superiortemporal_volume',
                'lh_supramarginal_volume',
                'lh_frontalpole_volume',
                'lh_temporalpole_volume',
                'lh_transversetemporal_volume',
                'lh_insula_volume',
                'rh_bankssts_volume',
                'rh_caudalanteriorcingulate_volume',
                'rh_caudalmiddlefrontal_volume',
                'rh_cuneus_volume',
                'rh_entorhinal_volume',
                'rh_fusiform_volume',
                'rh_inferiorparietal_volume',
                'rh_inferiortemporal_volume',
                'rh_isthmuscingulate_volume',
                'rh_lateraloccipital_volume',
                'rh_lateralorbitofrontal_volume',
                'rh_lingual_volume',
                'rh_medialorbitofrontal_volume',
                'rh_middletemporal_volume',
                'rh_parahippocampal_volume',
                'rh_paracentral_volume',
                'rh_parsopercularis_volume',
                'rh_parsorbitalis_volume',
                'rh_parstriangularis_volume',
                'rh_pericalcarine_volume',
                'rh_postcentral_volume',
                'rh_posteriorcingulate_volume',
                'rh_precentral_volume',
                'rh_precuneus_volume',
                'rh_rostralanteriorcingulate_volume',
                'rh_rostralmiddlefrontal_volume',
                'rh_superiorfrontal_volume',
                'rh_superiorparietal_volume',
                'rh_superiortemporal_volume',
                'rh_supramarginal_volume',
                'rh_frontalpole_volume',
                'rh_temporalpole_volume',
                'rh_transversetemporal_volume',
                'rh_insula_volume']
